### PR TITLE
Add instructions and easy batch script to make it easier for newbies

### PR DESCRIPTION
**Pull request by KillaBoi**
Hey Daniel,

I don't know if it would be useful at all but I made a Batch Script and added some instructions right at the bottom as I've seen a couple of issues opened as they don't know how to use it.

Let me know if any adjustments need to be made, I think it would be pretty helpful for those who are new and want to try it out.

### CODE REVIEW

**Comment by ghost** [comment]
Cool, but not everyone has python installed
Others do not know how to install it or maybe the PC is not theirs and they are not allowed to install it
Could it be make in C in an .exe?
For example, I use
https://github.com/danielkrupinski/curiuminjector-csgo
and I wish I could add it in there

Regards

**Comment by KillaBoi** [comment]
> Cool, but not everyone has python installed
> Others do not know how to install it or maybe the PC is not theirs and they are not allowed to install it
> Could it be make in C in an .exe?
> For example, I use
> https://github.com/danielkrupinski/curiuminjector-csgo
> and I wish I could add it in there
> 
> Regards

You can work with the implementations Daniel added in the readme to work that out

**Comment by ghost** [comment]
> > Cool, but not everyone has python installed
> > Others do not know how to install it or maybe the PC is not theirs and they are not allowed to install it
> > Could it be make in C in an .exe?
> > For example, I use
> > https://github.com/danielkrupinski/curiuminjector-csgo
> > and I wish I could add it in there
> > Regards
> 
> You can work with the implementations Daniel added in the readme to work that out

I have tried but it gives me error. I am new at this

**Review by danielkrupinski — COMMENTED** [review]
I don't think it's needed to provide script which just launches the python script.

**Pull request closed without merging**
